
/* File generated by gen_cfile.py. Should not be modified. */

#include "lpc11cxx_bl.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 Unlock_Code = 0x0;		/* Mapped at index 0x5000, subindex 0x00 */
UNS32 Mem_Rd_Addr = 0x0;		/* Mapped at index 0x5010, subindex 0x00 */
UNS32 Mem_Rd_Len = 0x0;		/* Mapped at index 0x5011, subindex 0x00 */
UNS32 RAM_Wr_Addr = 0x0;		/* Mapped at index 0x5015, subindex 0x00 */
UNS16 Prep_Sect = 0x0;		/* Mapped at index 0x5020, subindex 0x00 */
UNS16 Erase_Sect = 0x0;		/* Mapped at index 0x5030, subindex 0x00 */
UNS16 Blank_Chk_Sectors = 0x0;		/* Mapped at index 0x5040, subindex 0x01 */
UNS32 Blank_Chk_Offset = 0x0;		/* Mapped at index 0x5040, subindex 0x02 */
UNS32 Copy_RAM_to_Flash_Flash_Addr = 0x0;		/* Mapped at index 0x5050, subindex 0x01 */
UNS32 Copy_RAM_to_Flash_RAM_Addr = 0x0;		/* Mapped at index 0x5050, subindex 0x02 */
UNS16 Copy_RAM_to_Flash_Len = 0x0;		/* Mapped at index 0x5050, subindex 0x03 */
UNS32 Compare_Addr_Addr1 = 0x0;		/* Mapped at index 0x5060, subindex 0x01 */
UNS32 Compare_Addr_Addr2 = 0x0;		/* Mapped at index 0x5060, subindex 0x02 */
UNS16 Compare_Addr_Len = 0x0;		/* Mapped at index 0x5060, subindex 0x03 */
UNS32 Compare_Addr_Offset = 0x0;		/* Mapped at index 0x5060, subindex 0x04 */
UNS32 Exec_Addr_Addr = 0x0;		/* Mapped at index 0x5070, subindex 0x01 */
UNS8 Exec_Addr_Mode = 0x0;		/* Mapped at index 0x5070, subindex 0x02 */
UNS32 Serial_Number_S1 = 0x0;		/* Mapped at index 0x5100, subindex 0x01 */
UNS32 Serial_Number_S2 = 0x0;		/* Mapped at index 0x5100, subindex 0x02 */
UNS32 Serial_Number_S3 = 0x0;		/* Mapped at index 0x5100, subindex 0x03 */
UNS32 Serial_Number_S4 = 0x0;		/* Mapped at index 0x5100, subindex 0x04 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 lpc11cxx_bl_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 lpc11cxx_bl_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 lpc11cxx_bl_iam_a_slave = 0;

TIMER_HANDLE lpc11cxx_bl_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 lpc11cxx_bl_obj1000 = 0x0;	/* 0 */
                    ODCallback_t lpc11cxx_bl_Index1000_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&lpc11cxx_bl_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 lpc11cxx_bl_obj1001 = 0x0;	/* 0 */
                    ODCallback_t lpc11cxx_bl_Index1001_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&lpc11cxx_bl_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 lpc11cxx_bl_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 lpc11cxx_bl_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t lpc11cxx_bl_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&lpc11cxx_bl_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&lpc11cxx_bl_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 lpc11cxx_bl_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 lpc11cxx_bl_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 lpc11cxx_bl_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 lpc11cxx_bl_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 lpc11cxx_bl_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 lpc11cxx_bl_highestSubIndex_obj1016 = 0;
                    UNS32 lpc11cxx_bl_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 lpc11cxx_bl_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 lpc11cxx_bl_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 lpc11cxx_bl_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 lpc11cxx_bl_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 lpc11cxx_bl_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 lpc11cxx_bl_obj1018_Serial_Number = 0x0;	/* 0 */
                    ODCallback_t lpc11cxx_bl_Index1018_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&lpc11cxx_bl_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&lpc11cxx_bl_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&lpc11cxx_bl_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&lpc11cxx_bl_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&lpc11cxx_bl_obj1018_Serial_Number }
                     };

/* index 0x5000 :   Mapped variable Unlock Code */
                    subindex lpc11cxx_bl_Index5000[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Unlock_Code }
                     };

/* index 0x5010 :   Mapped variable Mem Rd Addr */
                    subindex lpc11cxx_bl_Index5010[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Mem_Rd_Addr }
                     };

/* index 0x5011 :   Mapped variable Mem Rd Len */
                    subindex lpc11cxx_bl_Index5011[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Mem_Rd_Len }
                     };

/* index 0x5015 :   Mapped variable RAM Wr Addr */
                    subindex lpc11cxx_bl_Index5015[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&RAM_Wr_Addr }
                     };

/* index 0x5020 :   Mapped variable Prep Sect */
                    subindex lpc11cxx_bl_Index5020[] = 
                     {
                       { WO, uint16, sizeof (UNS16), (void*)&Prep_Sect }
                     };

/* index 0x5030 :   Mapped variable Erase Sect */
                    subindex lpc11cxx_bl_Index5030[] = 
                     {
                       { WO, uint16, sizeof (UNS16), (void*)&Erase_Sect }
                     };

/* index 0x5040 :   Mapped variable Blank Chk */
                    UNS8 lpc11cxx_bl_highestSubIndex_obj5040 = 2; /* number of subindex - 1*/
                    ODCallback_t Blank_Chk_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index5040[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&lpc11cxx_bl_highestSubIndex_obj5040 },
                       { WO, uint16, sizeof (UNS16), (void*)&Blank_Chk_Sectors },
                       { RO, uint32, sizeof (UNS32), (void*)&Blank_Chk_Offset }
                     };

/* index 0x5050 :   Mapped variable Copy RAM to Flash */
                    UNS8 lpc11cxx_bl_highestSubIndex_obj5050 = 3; /* number of subindex - 1*/
                    ODCallback_t Copy_RAM_to_Flash_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index5050[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&lpc11cxx_bl_highestSubIndex_obj5050 },
                       { RW, uint32, sizeof (UNS32), (void*)&Copy_RAM_to_Flash_Flash_Addr },
                       { RW, uint32, sizeof (UNS32), (void*)&Copy_RAM_to_Flash_RAM_Addr },
                       { RW, uint16, sizeof (UNS16), (void*)&Copy_RAM_to_Flash_Len }
                     };

/* index 0x5060 :   Mapped variable Compare Addr */
                    UNS8 lpc11cxx_bl_highestSubIndex_obj5060 = 4; /* number of subindex - 1*/
                    ODCallback_t Compare_Addr_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index5060[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&lpc11cxx_bl_highestSubIndex_obj5060 },
                       { RW, uint32, sizeof (UNS32), (void*)&Compare_Addr_Addr1 },
                       { RW, uint32, sizeof (UNS32), (void*)&Compare_Addr_Addr2 },
                       { RW, uint16, sizeof (UNS16), (void*)&Compare_Addr_Len },
                       { RO, uint32, sizeof (UNS32), (void*)&Compare_Addr_Offset }
                     };

/* index 0x5070 :   Mapped variable Exec Addr */
                    UNS8 lpc11cxx_bl_highestSubIndex_obj5070 = 2; /* number of subindex - 1*/
                    ODCallback_t Exec_Addr_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index5070[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&lpc11cxx_bl_highestSubIndex_obj5070 },
                       { RW, uint32, sizeof (UNS32), (void*)&Exec_Addr_Addr },
                       { RO, uint8, sizeof (UNS8), (void*)&Exec_Addr_Mode }
                     };

/* index 0x5100 :   Mapped variable Serial Number */
                    UNS8 lpc11cxx_bl_highestSubIndex_obj5100 = 4; /* number of subindex - 1*/
                    ODCallback_t Serial_Number_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex lpc11cxx_bl_Index5100[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&lpc11cxx_bl_highestSubIndex_obj5100 },
                       { RO, uint32, sizeof (UNS32), (void*)&Serial_Number_S1 },
                       { RO, uint32, sizeof (UNS32), (void*)&Serial_Number_S2 },
                       { RO, uint32, sizeof (UNS32), (void*)&Serial_Number_S3 },
                       { RO, uint32, sizeof (UNS32), (void*)&Serial_Number_S4 }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable lpc11cxx_bl_objdict[] = 
{
  { (subindex*)lpc11cxx_bl_Index1000,sizeof(lpc11cxx_bl_Index1000)/sizeof(lpc11cxx_bl_Index1000[0]), 0x1000},
  { (subindex*)lpc11cxx_bl_Index1001,sizeof(lpc11cxx_bl_Index1001)/sizeof(lpc11cxx_bl_Index1001[0]), 0x1001},
  { (subindex*)lpc11cxx_bl_Index1018,sizeof(lpc11cxx_bl_Index1018)/sizeof(lpc11cxx_bl_Index1018[0]), 0x1018},
  { (subindex*)lpc11cxx_bl_Index5000,sizeof(lpc11cxx_bl_Index5000)/sizeof(lpc11cxx_bl_Index5000[0]), 0x5000},
  { (subindex*)lpc11cxx_bl_Index5010,sizeof(lpc11cxx_bl_Index5010)/sizeof(lpc11cxx_bl_Index5010[0]), 0x5010},
  { (subindex*)lpc11cxx_bl_Index5011,sizeof(lpc11cxx_bl_Index5011)/sizeof(lpc11cxx_bl_Index5011[0]), 0x5011},
  { (subindex*)lpc11cxx_bl_Index5015,sizeof(lpc11cxx_bl_Index5015)/sizeof(lpc11cxx_bl_Index5015[0]), 0x5015},
  { (subindex*)lpc11cxx_bl_Index5020,sizeof(lpc11cxx_bl_Index5020)/sizeof(lpc11cxx_bl_Index5020[0]), 0x5020},
  { (subindex*)lpc11cxx_bl_Index5030,sizeof(lpc11cxx_bl_Index5030)/sizeof(lpc11cxx_bl_Index5030[0]), 0x5030},
  { (subindex*)lpc11cxx_bl_Index5040,sizeof(lpc11cxx_bl_Index5040)/sizeof(lpc11cxx_bl_Index5040[0]), 0x5040},
  { (subindex*)lpc11cxx_bl_Index5050,sizeof(lpc11cxx_bl_Index5050)/sizeof(lpc11cxx_bl_Index5050[0]), 0x5050},
  { (subindex*)lpc11cxx_bl_Index5060,sizeof(lpc11cxx_bl_Index5060)/sizeof(lpc11cxx_bl_Index5060[0]), 0x5060},
  { (subindex*)lpc11cxx_bl_Index5070,sizeof(lpc11cxx_bl_Index5070)/sizeof(lpc11cxx_bl_Index5070[0]), 0x5070},
  { (subindex*)lpc11cxx_bl_Index5100,sizeof(lpc11cxx_bl_Index5100)/sizeof(lpc11cxx_bl_Index5100[0]), 0x5100},
};

const indextable * lpc11cxx_bl_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;*callbacks = lpc11cxx_bl_Index1000_callbacks; break;
		case 0x1001: i = 1;*callbacks = lpc11cxx_bl_Index1001_callbacks; break;
		case 0x1018: i = 2;*callbacks = lpc11cxx_bl_Index1018_callbacks; break;
		case 0x5000: i = 3;break;
		case 0x5010: i = 4;break;
		case 0x5011: i = 5;break;
		case 0x5015: i = 6;break;
		case 0x5020: i = 7;break;
		case 0x5030: i = 8;break;
		case 0x5040: i = 9;*callbacks = Blank_Chk_callbacks; break;
		case 0x5050: i = 10;*callbacks = Copy_RAM_to_Flash_callbacks; break;
		case 0x5060: i = 11;*callbacks = Compare_Addr_callbacks; break;
		case 0x5070: i = 12;*callbacks = Exec_Addr_callbacks; break;
		case 0x5100: i = 13;*callbacks = Serial_Number_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &lpc11cxx_bl_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status lpc11cxx_bl_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index lpc11cxx_bl_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index lpc11cxx_bl_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 lpc11cxx_bl_ObjdictSize = sizeof(lpc11cxx_bl_objdict)/sizeof(lpc11cxx_bl_objdict[0]); 

CO_Data lpc11cxx_bl_Data = CANOPEN_NODE_DATA_INITIALIZER(lpc11cxx_bl);

