
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef LPC11CXX_BL_H
#define LPC11CXX_BL_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 lpc11cxx_bl_valueRangeTest (UNS8 typeValue, void * value);
const indextable * lpc11cxx_bl_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data lpc11cxx_bl_Data;
extern UNS16 Unlock_Code;		/* Mapped at index 0x5000, subindex 0x00*/
extern UNS32 Mem_Rd_Addr;		/* Mapped at index 0x5010, subindex 0x00*/
extern UNS32 Mem_Rd_Len;		/* Mapped at index 0x5011, subindex 0x00*/
extern UNS32 RAM_Wr_Addr;		/* Mapped at index 0x5015, subindex 0x00*/
extern UNS16 Prep_Sect;		/* Mapped at index 0x5020, subindex 0x00*/
extern UNS16 Erase_Sect;		/* Mapped at index 0x5030, subindex 0x00*/
extern UNS16 Blank_Chk_Sectors;		/* Mapped at index 0x5040, subindex 0x01 */
extern UNS32 Blank_Chk_Offset;		/* Mapped at index 0x5040, subindex 0x02 */
extern UNS32 Copy_RAM_to_Flash_Flash_Addr;		/* Mapped at index 0x5050, subindex 0x01 */
extern UNS32 Copy_RAM_to_Flash_RAM_Addr;		/* Mapped at index 0x5050, subindex 0x02 */
extern UNS16 Copy_RAM_to_Flash_Len;		/* Mapped at index 0x5050, subindex 0x03 */
extern UNS32 Compare_Addr_Addr1;		/* Mapped at index 0x5060, subindex 0x01 */
extern UNS32 Compare_Addr_Addr2;		/* Mapped at index 0x5060, subindex 0x02 */
extern UNS16 Compare_Addr_Len;		/* Mapped at index 0x5060, subindex 0x03 */
extern UNS32 Compare_Addr_Offset;		/* Mapped at index 0x5060, subindex 0x04 */
extern UNS32 Exec_Addr_Addr;		/* Mapped at index 0x5070, subindex 0x01 */
extern UNS8 Exec_Addr_Mode;		/* Mapped at index 0x5070, subindex 0x02 */
extern UNS32 Serial_Number_S1;		/* Mapped at index 0x5100, subindex 0x01 */
extern UNS32 Serial_Number_S2;		/* Mapped at index 0x5100, subindex 0x02 */
extern UNS32 Serial_Number_S3;		/* Mapped at index 0x5100, subindex 0x03 */
extern UNS32 Serial_Number_S4;		/* Mapped at index 0x5100, subindex 0x04 */

#endif // LPC11CXX_BL_H
